# ===================================
#  List Behavior Config
# ===================================

title: void.match::lang.matches.list_title
list: ~/plugins/void/match/models/match/columns.yaml
modelClass: Void\Match\Models\Match
recordUrl: void/match/matches/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



